sudo: false
language: node_js
node_js:
  - stable
install:
  - npm install
notifications:
  email: false
services:
  - mongodb
before_script:
  - sleep 15
  - mongo meme-it-test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - 'npm run test'